set_property SRC_FILE_INFO {cfile:{C:/Users/Kumar Lab/Desktop/Shannon/clock_test_ex/clock_test_ex.gen/sources_1/ip/clock_test/clock_test/example_design/clock_test_exdes.xdc} rfile:../../../clock_test_ex.gen/sources_1/ip/clock_test/clock_test/example_design/clock_test_exdes.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/Kumar Lab/Desktop/Shannon/clock_test_ex/clock_test_ex.srcs/constrs_1/new/qwn_io_supp.xdc} rfile:../../../clock_test_ex.srcs/constrs_1/new/qwn_io_supp.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK7 [get_ports  Q3_CLK1_GTREFCLK_PAD_N_IN ]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AK8 [get_ports  Q3_CLK1_GTREFCLK_PAD_P_IN ]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC H19 [get_ports  DRP_CLK_IN_P]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G18 [get_ports  DRP_CLK_IN_N]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y12 [get_cells clock_test_support_i/clock_test_init_i/inst/clock_test_i/gt0_clock_test_i/gthe2_i]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y13 [get_cells clock_test_support_i/clock_test_init_i/inst/clock_test_i/gt1_clock_test_i/gthe2_i]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y14 [get_cells clock_test_support_i/clock_test_init_i/inst/clock_test_i/gt2_clock_test_i/gthe2_i]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y15 [get_cells clock_test_support_i/clock_test_init_i/inst/clock_test_i/gt3_clock_test_i/gthe2_i]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_pins -filter {REF_PIN_NAME=~*O} -of_objects [get_cells -hierarchical -filter {NAME =~ *DRP_CLK_BUFG*}]]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J40        [get_ports TRACK_DATA_OUT]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK34 [get_ports SYSCLK_IN_P]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL34 [get_ports SYSCLK_IN_N]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ32 [get_ports ref_clk_true_p]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK32 [get_ports ref_clk_true_n]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB41     [get_ports SFP0_TX_DISABLE]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W40      [get_ports SFP0_RS0]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M36      [get_ports ALWAYS_ON]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y40      [get_ports SFP0_RS1]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y38      [get_ports SFP0_TX_FAULT]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y39      [get_ports SFP0_RX_LOS]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB42     [get_ports SFP0_MOD_ABS]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA42     [get_ports SFP2_MOD_ABS]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC39     [get_ports SFP3_MOD_ABS]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC41     [get_ports SFP4_MOD_ABS]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y42      [get_ports SFP1_TX_DISABLE]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB38     [get_ports SFP1_RS0]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA40     [get_ports SFP1_RX_LOS]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N41      [get_ports RX_PAYLOAD_MARK_SIGNAL]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H41      [get_ports RX_PAYLOAD_MARK_IDLER]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC38     [get_ports SFP3_TX_DISABLE]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD42     [get_ports SFP3_RS0]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H31      [get_ports TX_PAYLOAD_REF]
