///////////////////////////////////////////////////////////////////////////////
//   ____  ____
//  /   /\/   / 
// /___/  \  /    Vendor: AMD 
// \   \   \/     Version : 3.6
//  \   \         Application : 7 Series FPGAs Transceivers  Wizard
//  /   /         Filename : clock_test_gt_usrclk_source.v
// /___/   /\      
// \   \  /  \ 
//  \___\/\___\ 
//
//
// Module clock_test_GT_USRCLK_SOURCE (for use with GTs)
// Generated by AMD 7 Series FPGAs Transceivers Wizard
// 
// 
// (c) Copyright 2023 Advanced Micro Devices, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of AMD, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// AMD, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND AMD HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) AMD shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or AMD had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// AMD products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of AMD products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


/*=============================================================================
 * *** HAND-EDITED GENERATED FILE -- DO NOT REGENERATE THE clock_test IP ***
 * Regenerating (or re-running generate_target on) the clock_test wizard IP
 * rewrites this file and silently DELETES the QWN edits below. If you must
 * regenerate, diff against this copy and re-apply every line tagged
 * "B10 QWN", "QWN" or "gt1 INDEPENDENT". A .predoc snapshot of this exact
 * file sits next to it.
 *
 * QWN edits carried by this file (top-level story in qwn_exdes.v header):
 *  1. B10 (p_b10/p_b11_2026-06-10, marker-jitter campaign): export the gt0
 *     RX MMCM's 625 MHz CLK2_OUT as GT0_RXUSRCLK625_OUT. The wizard always
 *     generated a divide-1 (=VCO) CLK2 output, internally BUFG'd inside
 *     clock_test_CLOCK_MODULE, and left it UNCONNECTED -- B10 simply wires
 *     it out. Purpose: clock the marker OSERDESE2 pair (CLK=625, CLKDIV=
 *     rxusrclk2=156.25) from the SAME MMCM, deleting the cascaded marker
 *     MMCM + 3 BUFGs and the rxusrclk2->mk156 capture crossing. Same-MMCM
 *     pairing is also what makes the CLOCK_DELAY_GROUP matched-insertion
 *     constraint meaningful (qwn_bufferless.xdc).
 *  2. Dual-lane (2026-05-18 builds): gt1 got its OWN TX+RX MMCM pair
 *     (txoutclk_mmcm2/rxoutclk_mmcm3) instead of piggybacking gt0's --
 *     bufferless buffer-bypass needs per-lane recovered clocks. gt2/gt3
 *     still piggyback gt0 (see the output assigns at the bottom): that is
 *     DELIBERATE -- the X1Y3 clock-region 12-track ceiling makes a third
 *     full RX lane unplaceable; gt2 is TX-only off gt0's TX clocks.
 *
 * Sim/HW evidence: B10/B11 close timing and JTAG-validate (lock + fire
 * counters); rxusrclk625 lock is observable as hist idx15 via probe_in17.
 *===========================================================================*/

`timescale 1ns / 1ps

//***********************************Entity Declaration*******************************

module clock_test_GT_USRCLK_SOURCE 
(
 
    output          GT0_TXUSRCLK_OUT,
    output          GT0_TXUSRCLK2_OUT,
    input           GT0_TXOUTCLK_IN,
    output          GT0_TXCLK_LOCK_OUT,
    input           GT0_TX_MMCM_RESET_IN,
    output          GT0_RXUSRCLK_OUT,
    output          GT0_RXUSRCLK2_OUT,
    input           GT0_RXOUTCLK_IN,
    output          GT0_RXCLK_LOCK_OUT,
    // B10 (QWN): 625 MHz from the gt0 RX MMCM VCO (OUT2_DIVIDE=1, BUFG'd
    // in CLOCK_MODULE) -- OSERDES CLK paired with rxusrclk2 (same MMCM,
    // no cascade). EDITED GENERATED FILE: do not regenerate clock_test IP.
    output          GT0_RXUSRCLK625_OUT,
    input           GT0_RX_MMCM_RESET_IN,
 
    output          GT1_TXUSRCLK_OUT,
    output          GT1_TXUSRCLK2_OUT,
    input           GT1_TXOUTCLK_IN,
    output          GT1_TXCLK_LOCK_OUT,
    input           GT1_TX_MMCM_RESET_IN,
    output          GT1_RXUSRCLK_OUT,
    output          GT1_RXUSRCLK2_OUT,
    input           GT1_RXOUTCLK_IN,
    output          GT1_RXCLK_LOCK_OUT,
    input           GT1_RX_MMCM_RESET_IN,
 
    output          GT2_TXUSRCLK_OUT,
    output          GT2_TXUSRCLK2_OUT,
    input           GT2_TXOUTCLK_IN,
    output          GT2_TXCLK_LOCK_OUT,
    input           GT2_TX_MMCM_RESET_IN,
    output          GT2_RXUSRCLK_OUT,
    output          GT2_RXUSRCLK2_OUT,
    input           GT2_RXOUTCLK_IN,
    output          GT2_RXCLK_LOCK_OUT,
    input           GT2_RX_MMCM_RESET_IN,
 
    output          GT3_TXUSRCLK_OUT,
    output          GT3_TXUSRCLK2_OUT,
    input           GT3_TXOUTCLK_IN,
    output          GT3_TXCLK_LOCK_OUT,
    input           GT3_TX_MMCM_RESET_IN,
    output          GT3_RXUSRCLK_OUT,
    output          GT3_RXUSRCLK2_OUT,
    input           GT3_RXOUTCLK_IN,
    output          GT3_RXCLK_LOCK_OUT,
    input           GT3_RX_MMCM_RESET_IN,
    input  wire  Q3_CLK1_GTREFCLK_PAD_N_IN,
    input  wire  Q3_CLK1_GTREFCLK_PAD_P_IN,
    output wire  Q3_CLK1_GTREFCLK_OUT



);


`define DLY #1

//*********************************Wire Declarations**********************************
    wire            tied_to_ground_i;
    wire            tied_to_vcc_i;
 
    wire            gt0_txoutclk_i; 
    wire            gt0_rxoutclk_i;
 
    wire            gt1_txoutclk_i; 
    wire            gt1_rxoutclk_i;
 
    wire            gt2_txoutclk_i; 
    wire            gt2_rxoutclk_i;
 
    wire            gt3_txoutclk_i; 
    wire            gt3_rxoutclk_i;
    wire  q3_clk1_gtrefclk /*synthesis syn_noclockbuf=1*/;

    wire            gt0_txusrclk_i;
    wire            gt0_txusrclk2_i;
    wire            gt0_rxusrclk_i;
    wire            gt0_rxusrclk2_i;
    wire            txoutclk_mmcm0_locked_i;
    wire            txoutclk_mmcm0_reset_i;
    wire            gt0_txoutclk_to_mmcm_i;
    wire            rxoutclk_mmcm1_locked_i;
    wire            gt0_rxusrclk625_i;   // B10 QWN
    wire            rxoutclk_mmcm1_reset_i;
    wire            gt0_rxoutclk_to_mmcm_i;
    // --- gt1 INDEPENDENT clocking (dual-lane: cross-SFP TX1<->RX2). Purely
    //     additive; gt0 mmcm0/mmcm1 untouched -> lane-0 zero regression. ---
    wire            gt1_txusrclk_i;
    wire            gt1_txusrclk2_i;
    wire            gt1_rxusrclk_i;
    wire            gt1_rxusrclk2_i;
    wire            txoutclk_mmcm2_locked_i;
    wire            txoutclk_mmcm2_reset_i;
    wire            rxoutclk_mmcm3_locked_i;
    wire            rxoutclk_mmcm3_reset_i;


//*********************************** Beginning of Code *******************************

    //  Static signal Assigments    
    assign tied_to_ground_i             = 1'b0;
    assign tied_to_vcc_i                = 1'b1;
    assign gt0_txoutclk_i = GT0_TXOUTCLK_IN;
    assign gt0_rxoutclk_i = GT0_RXOUTCLK_IN;
    assign gt1_txoutclk_i = GT1_TXOUTCLK_IN;
    assign gt1_rxoutclk_i = GT1_RXOUTCLK_IN;
    assign gt2_txoutclk_i = GT2_TXOUTCLK_IN;
    assign gt2_rxoutclk_i = GT2_RXOUTCLK_IN;
    assign gt3_txoutclk_i = GT3_TXOUTCLK_IN;
    assign gt3_rxoutclk_i = GT3_RXOUTCLK_IN;
     
    assign Q3_CLK1_GTREFCLK_OUT = q3_clk1_gtrefclk;

    //IBUFDS_GTE2
    IBUFDS_GTE2 ibufds_instQ3_CLK1  
    (
        .O               (q3_clk1_gtrefclk),
        .ODIV2           (),
        .CEB             (tied_to_ground_i),
        .I               (Q3_CLK1_GTREFCLK_PAD_P_IN),
        .IB              (Q3_CLK1_GTREFCLK_PAD_N_IN)
    );



    // Instantiate a MMCM module to divide the reference clock. Uses internal feedback
    // for improved jitter performance, and to avoid consuming an additional BUFG

    assign  txoutclk_mmcm0_reset_i               =  GT0_TX_MMCM_RESET_IN;
    clock_test_CLOCK_MODULE #
    (
        .MULT                           (4.0),
        .DIVIDE                         (1),
        .CLK_PERIOD                     (6.4),
        .OUT0_DIVIDE                    (32.0),
        .OUT1_DIVIDE                    (16),
        .OUT2_DIVIDE                    (1),
        .OUT3_DIVIDE                    (1)
    )
    txoutclk_mmcm0_i
    (
        .CLK0_OUT                       (gt0_txusrclk2_i),
        .CLK1_OUT                       (gt0_txusrclk_i),
        .CLK2_OUT                       (),
        .CLK3_OUT                       (),
        .CLK_IN                         (gt0_txoutclk_i),
        .MMCM_LOCKED_OUT                (txoutclk_mmcm0_locked_i),
        .MMCM_RESET_IN                  (txoutclk_mmcm0_reset_i)
    );


    assign  rxoutclk_mmcm1_reset_i               =  GT0_RX_MMCM_RESET_IN;
    // B10 QWN region -- gt0 RX MMCM (generated instance; the ONLY edit is
    // the CLK2_OUT hookup below). The arithmetic that makes B10 free:
    //   CLK_IN  = gt0 RXOUTCLK = RXOUTCLKPMA = recovered clock, 312.5 MHz
    //             (CLK_PERIOD 3.2 ns) -- the RX divider output that carries
    //             the per-re-lock UI phase (see campaign brief topic 1).
    //   VCO     = 312.5 x MULT 2.0 / DIVIDE 1 = exactly 625 MHz.
    //   CLK0    = VCO/4 = 156.25 MHz -> gt0_rxusrclk2 (64-bit word clock)
    //   CLK1    = VCO/2 = 312.5 MHz  -> gt0_rxusrclk
    //   CLK2    = VCO/1 = 625 MHz    -> gt0_rxusrclk625 (B10: was unwired)
    // 625 MHz is BOTH the OSERDES DDR bit clock (800 ps/UI at 8 UI/word)
    // AND the native VCO -- so the marker bit clock costs zero extra MMCM.
    // CLOCK_MODULE BUFGs all outputs and feeds CLKFBOUT back through a BUFG
    // (deskew: outputs phase-true to CLK_IN at the fabric -- see the MMCM
    // basics aside in qwn_exdes.v); all three outputs are zero-phase from
    // one VCO, the precondition for the OSERDES CLK/CLKDIV pairing rule.
    clock_test_CLOCK_MODULE #
    (
        .MULT                           (2.0),
        .DIVIDE                         (1),
        .CLK_PERIOD                     (3.2),
        .OUT0_DIVIDE                    (4.0),
        .OUT1_DIVIDE                    (2),
        .OUT2_DIVIDE                    (1),
        .OUT3_DIVIDE                    (1)
    )
    rxoutclk_mmcm1_i
    (
        .CLK0_OUT                       (gt0_rxusrclk2_i),
        .CLK1_OUT                       (gt0_rxusrclk_i),
        .CLK2_OUT                       (gt0_rxusrclk625_i),
        .CLK3_OUT                       (),
        .CLK_IN                         (gt0_rxoutclk_i),
        .MMCM_LOCKED_OUT                (rxoutclk_mmcm1_locked_i),
        .MMCM_RESET_IN                  (rxoutclk_mmcm1_reset_i)
    );

    // ===== gt1 independent TX+RX MMCMs (exact mirror of gt0's) =====
    assign  txoutclk_mmcm2_reset_i               =  GT1_TX_MMCM_RESET_IN;
    clock_test_CLOCK_MODULE #
    (
        .MULT                           (4.0),
        .DIVIDE                         (1),
        .CLK_PERIOD                     (6.4),
        .OUT0_DIVIDE                    (32.0),
        .OUT1_DIVIDE                    (16),
        .OUT2_DIVIDE                    (1),
        .OUT3_DIVIDE                    (1)
    )
    txoutclk_mmcm2_i
    (
        .CLK0_OUT                       (gt1_txusrclk2_i),
        .CLK1_OUT                       (gt1_txusrclk_i),
        .CLK2_OUT                       (),
        .CLK3_OUT                       (),
        .CLK_IN                         (gt1_txoutclk_i),
        .MMCM_LOCKED_OUT                (txoutclk_mmcm2_locked_i),
        .MMCM_RESET_IN                  (txoutclk_mmcm2_reset_i)
    );

    assign  rxoutclk_mmcm3_reset_i               =  GT1_RX_MMCM_RESET_IN;
    clock_test_CLOCK_MODULE #
    (
        .MULT                           (2.0),
        .DIVIDE                         (1),
        .CLK_PERIOD                     (3.2),
        .OUT0_DIVIDE                    (4.0),
        .OUT1_DIVIDE                    (2),
        .OUT2_DIVIDE                    (1),
        .OUT3_DIVIDE                    (1)
    )
    rxoutclk_mmcm3_i
    (
        .CLK0_OUT                       (gt1_rxusrclk2_i),
        .CLK1_OUT                       (gt1_rxusrclk_i),
        .CLK2_OUT                       (),
        .CLK3_OUT                       (),
        .CLK_IN                         (gt1_rxoutclk_i),
        .MMCM_LOCKED_OUT                (rxoutclk_mmcm3_locked_i),
        .MMCM_RESET_IN                  (rxoutclk_mmcm3_reset_i)
    );



 
assign GT0_TXUSRCLK_OUT = gt0_txusrclk_i;
assign GT0_TXUSRCLK2_OUT = gt0_txusrclk2_i;
assign GT0_TXCLK_LOCK_OUT = txoutclk_mmcm0_locked_i;
assign GT0_RXUSRCLK_OUT = gt0_rxusrclk_i;
assign GT0_RXUSRCLK625_OUT = gt0_rxusrclk625_i;   // B10 QWN
assign GT0_RXUSRCLK2_OUT = gt0_rxusrclk2_i;
assign GT0_RXCLK_LOCK_OUT = rxoutclk_mmcm1_locked_i;
 
assign GT1_TXUSRCLK_OUT = gt1_txusrclk_i;          // gt1 INDEPENDENT clocks
assign GT1_TXUSRCLK2_OUT = gt1_txusrclk2_i;
assign GT1_TXCLK_LOCK_OUT = txoutclk_mmcm2_locked_i;
assign GT1_RXUSRCLK_OUT = gt1_rxusrclk_i;
assign GT1_RXUSRCLK2_OUT = gt1_rxusrclk2_i;
assign GT1_RXCLK_LOCK_OUT = rxoutclk_mmcm3_locked_i;
 
assign GT2_TXUSRCLK_OUT = gt0_txusrclk_i;
assign GT2_TXUSRCLK2_OUT = gt0_txusrclk2_i;
assign GT2_TXCLK_LOCK_OUT = txoutclk_mmcm0_locked_i;
assign GT2_RXUSRCLK_OUT = gt0_rxusrclk_i;
assign GT2_RXUSRCLK2_OUT = gt0_rxusrclk2_i;
assign GT2_RXCLK_LOCK_OUT = rxoutclk_mmcm1_locked_i;
 
assign GT3_TXUSRCLK_OUT = gt0_txusrclk_i;
assign GT3_TXUSRCLK2_OUT = gt0_txusrclk2_i;
assign GT3_TXCLK_LOCK_OUT = txoutclk_mmcm0_locked_i;
assign GT3_RXUSRCLK_OUT = gt0_rxusrclk_i;
assign GT3_RXUSRCLK2_OUT = gt0_rxusrclk2_i;
assign GT3_RXCLK_LOCK_OUT = rxoutclk_mmcm1_locked_i;

endmodule
