# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Kumar Lab/Desktop/Shannon/clock_test_ex/clock_test_ex.srcs/sources_1/ip/clock_test/clock_test.xci
# IP: The module: 'clock_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Kumar Lab/Desktop/Shannon/clock_test_ex/clock_test_ex.gen/sources_1/ip/clock_test/clock_test.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_test'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Kumar Lab/Desktop/Shannon/clock_test_ex/clock_test_ex.gen/sources_1/ip/clock_test/clock_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Kumar Lab/Desktop/Shannon/clock_test_ex/clock_test_ex.srcs/sources_1/ip/clock_test/clock_test.xci
# IP: The module: 'clock_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Kumar Lab/Desktop/Shannon/clock_test_ex/clock_test_ex.gen/sources_1/ip/clock_test/clock_test.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Kumar Lab/Desktop/Shannon/clock_test_ex/clock_test_ex.gen/sources_1/ip/clock_test/clock_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
