///////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   /
// /___/  \  /    Vendor: AMD
// \   \   \/     Version : 3.6
//  \   \         Application : 7 Series FPGAs Transceivers Wizard
//  /   /         Filename : clock_test_multi_gt.v
// /___/   /\     
// \   \  /  \ 
//  \___\/\___\
//
//
// Module clock_test_multi_gt (a Multi GT Wrapper)
// Generated by AMD 7 Series FPGAs Transceivers Wizard
// 
// 
// (c) Copyright 2023 Advanced Micro Devices, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of AMD, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// AMD, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND AMD HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) AMD shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or AMD had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// AMD products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of AMD products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`default_nettype wire

`timescale 1ns / 1ps
`define DLY #1

//***************************** Entity Declaration ****************************
(* DowngradeIPIdentifiedWarnings="yes" *)
(* CORE_GENERATION_INFO = "clock_test_multi_gt,gtwizard_v3_6_15,{protocol_file=Start_from_scratch}" *) module clock_test_multi_gt #
(
    // Simulation attributes
    parameter   EXAMPLE_SIMULATION       =   0,             // Set to 1 for Simulation
    parameter   WRAPPER_SIM_GTRESET_SPEEDUP    = "FALSE"    // Set to "TRUE" to speed up sim reset
)
(
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT0  (X0Y12)
    //____________________________CHANNEL PORTS________________________________
output gt0_rxpmaresetdone_out,
output gt0_txpmaresetdone_out,
    //------------------------ Channel - Clocking Ports ------------------------
    input           gt0_gtnorthrefclk0_in,
    input           gt0_gtnorthrefclk1_in,
    input           gt0_gtsouthrefclk0_in,
    input           gt0_gtsouthrefclk1_in,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   gt0_drpaddr_in,
    input           gt0_drpclk_in,
    input   [15:0]  gt0_drpdi_in,
    output  [15:0]  gt0_drpdo_out,
    input           gt0_drpen_in,
    output          gt0_drprdy_out,
    input           gt0_drpwe_in,
    //----------------------------- Clocking Ports -----------------------------
    input   [1:0]   gt0_rxsysclksel_in,
    input   [1:0]   gt0_txsysclksel_in,
    //----------------------------- Loopback Ports -----------------------------
    input   [2:0]   gt0_loopback_in,
    //------------------- RX Initialization and Reset Ports --------------------
    input           gt0_eyescanreset_in,
    input           gt0_rxuserrdy_in,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          gt0_eyescandataerror_out,
    input           gt0_eyescantrigger_in,
    //----------------------- Receive Ports - CDR Ports ------------------------
    input           gt0_rxcdrhold_in,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    input           gt0_rxslide_in,
    //----------------- Receive Ports - Digital Monitor Ports ------------------
    output  [14:0]  gt0_dmonitorout_out,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           gt0_rxusrclk_in,
    input           gt0_rxusrclk2_in,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [63:0]  gt0_rxdata_out,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           gt0_gthrxn_in,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           gt0_rxdlyen_in,
    input           gt0_rxdlysreset_in,
    output          gt0_rxdlysresetdone_out,
    input           gt0_rxphalign_in,
    output          gt0_rxphaligndone_out,
    input           gt0_rxphalignen_in,
    input           gt0_rxphdlyreset_in,
    output  [4:0]   gt0_rxphmonitor_out,
    output  [4:0]   gt0_rxphslipmonitor_out,
    input           gt0_rxsyncallin_in,
    output          gt0_rxsyncdone_out,
    input           gt0_rxsyncin_in,
    input           gt0_rxsyncmode_in,
    output          gt0_rxsyncout_out,
    //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
    output          gt0_rxbyteisaligned_out,
    output          gt0_rxbyterealign_out,
    output          gt0_rxcommadet_out,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           gt0_rxdfeagchold_in,
    input           gt0_rxdfelfhold_in,
    output  [6:0]   gt0_rxmonitorout_out,
    input   [1:0]   gt0_rxmonitorsel_in,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          gt0_rxoutclk_out,
    output          gt0_rxoutclkfabric_out,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           gt0_gtrxreset_in,
    //---------------------- Receive Ports -RX AFE Ports -----------------------
    input           gt0_gthrxp_in,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          gt0_rxresetdone_out,
    //------------------- TX Initialization and Reset Ports --------------------
    input           gt0_gttxreset_in,
    input           gt0_txuserrdy_in,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           gt0_txusrclk_in,
    input           gt0_txusrclk2_in,
    //---------------- Transmit Ports - TX Buffer Bypass Ports -----------------
    input           gt0_txdlyen_in,
    input           gt0_txdlysreset_in,
    output          gt0_txdlysresetdone_out,
    input           gt0_txphalign_in,
    output          gt0_txphaligndone_out,
    input           gt0_txphalignen_in,
    input           gt0_txphdlyreset_in,
    input           gt0_txphinit_in,
    output          gt0_txphinitdone_out,
    //------------- Transmit Ports - TX Configurable Driver Ports --------------
    input           gt0_txinhibit_in,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [63:0]  gt0_txdata_in,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          gt0_gthtxn_out,
    output          gt0_gthtxp_out,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          gt0_txoutclk_out,
    output          gt0_txoutclkfabric_out,
    output          gt0_txoutclkpcs_out,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          gt0_txresetdone_out,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT1  (X0Y13)
    //____________________________CHANNEL PORTS________________________________
output gt1_rxpmaresetdone_out,
output gt1_txpmaresetdone_out,
    //------------------------ Channel - Clocking Ports ------------------------
    input           gt1_gtnorthrefclk0_in,
    input           gt1_gtnorthrefclk1_in,
    input           gt1_gtsouthrefclk0_in,
    input           gt1_gtsouthrefclk1_in,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   gt1_drpaddr_in,
    input           gt1_drpclk_in,
    input   [15:0]  gt1_drpdi_in,
    output  [15:0]  gt1_drpdo_out,
    input           gt1_drpen_in,
    output          gt1_drprdy_out,
    input           gt1_drpwe_in,
    //----------------------------- Clocking Ports -----------------------------
    input   [1:0]   gt1_rxsysclksel_in,
    input   [1:0]   gt1_txsysclksel_in,
    //----------------------------- Loopback Ports -----------------------------
    input   [2:0]   gt1_loopback_in,
    //------------------- RX Initialization and Reset Ports --------------------
    input           gt1_eyescanreset_in,
    input           gt1_rxuserrdy_in,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          gt1_eyescandataerror_out,
    input           gt1_eyescantrigger_in,
    //----------------------- Receive Ports - CDR Ports ------------------------
    input           gt1_rxcdrhold_in,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    input           gt1_rxslide_in,
    //----------------- Receive Ports - Digital Monitor Ports ------------------
    output  [14:0]  gt1_dmonitorout_out,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           gt1_rxusrclk_in,
    input           gt1_rxusrclk2_in,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [63:0]  gt1_rxdata_out,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           gt1_gthrxn_in,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           gt1_rxdlyen_in,
    input           gt1_rxdlysreset_in,
    output          gt1_rxdlysresetdone_out,
    input           gt1_rxphalign_in,
    output          gt1_rxphaligndone_out,
    input           gt1_rxphalignen_in,
    input           gt1_rxphdlyreset_in,
    output  [4:0]   gt1_rxphmonitor_out,
    output  [4:0]   gt1_rxphslipmonitor_out,
    input           gt1_rxsyncallin_in,
    output          gt1_rxsyncdone_out,
    input           gt1_rxsyncin_in,
    input           gt1_rxsyncmode_in,
    output          gt1_rxsyncout_out,
    //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
    output          gt1_rxbyteisaligned_out,
    output          gt1_rxbyterealign_out,
    output          gt1_rxcommadet_out,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           gt1_rxdfeagchold_in,
    input           gt1_rxdfelfhold_in,
    output  [6:0]   gt1_rxmonitorout_out,
    input   [1:0]   gt1_rxmonitorsel_in,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          gt1_rxoutclk_out,
    output          gt1_rxoutclkfabric_out,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           gt1_gtrxreset_in,
    //---------------------- Receive Ports -RX AFE Ports -----------------------
    input           gt1_gthrxp_in,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          gt1_rxresetdone_out,
    //------------------- TX Initialization and Reset Ports --------------------
    input           gt1_gttxreset_in,
    input           gt1_txuserrdy_in,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           gt1_txusrclk_in,
    input           gt1_txusrclk2_in,
    //---------------- Transmit Ports - TX Buffer Bypass Ports -----------------
    input           gt1_txdlyen_in,
    input           gt1_txdlysreset_in,
    output          gt1_txdlysresetdone_out,
    input           gt1_txphalign_in,
    output          gt1_txphaligndone_out,
    input           gt1_txphalignen_in,
    input           gt1_txphdlyreset_in,
    input           gt1_txphinit_in,
    output          gt1_txphinitdone_out,
    //------------- Transmit Ports - TX Configurable Driver Ports --------------
    input           gt1_txinhibit_in,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [63:0]  gt1_txdata_in,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          gt1_gthtxn_out,
    output          gt1_gthtxp_out,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          gt1_txoutclk_out,
    output          gt1_txoutclkfabric_out,
    output          gt1_txoutclkpcs_out,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          gt1_txresetdone_out,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT2  (X0Y14)
    //____________________________CHANNEL PORTS________________________________
output gt2_rxpmaresetdone_out,
output gt2_txpmaresetdone_out,
    //------------------------ Channel - Clocking Ports ------------------------
    input           gt2_gtnorthrefclk0_in,
    input           gt2_gtnorthrefclk1_in,
    input           gt2_gtsouthrefclk0_in,
    input           gt2_gtsouthrefclk1_in,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   gt2_drpaddr_in,
    input           gt2_drpclk_in,
    input   [15:0]  gt2_drpdi_in,
    output  [15:0]  gt2_drpdo_out,
    input           gt2_drpen_in,
    output          gt2_drprdy_out,
    input           gt2_drpwe_in,
    //----------------------------- Clocking Ports -----------------------------
    input   [1:0]   gt2_rxsysclksel_in,
    input   [1:0]   gt2_txsysclksel_in,
    //----------------------------- Loopback Ports -----------------------------
    input   [2:0]   gt2_loopback_in,
    //------------------- RX Initialization and Reset Ports --------------------
    input           gt2_eyescanreset_in,
    input           gt2_rxuserrdy_in,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          gt2_eyescandataerror_out,
    input           gt2_eyescantrigger_in,
    //----------------------- Receive Ports - CDR Ports ------------------------
    input           gt2_rxcdrhold_in,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    input           gt2_rxslide_in,
    //----------------- Receive Ports - Digital Monitor Ports ------------------
    output  [14:0]  gt2_dmonitorout_out,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           gt2_rxusrclk_in,
    input           gt2_rxusrclk2_in,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [63:0]  gt2_rxdata_out,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           gt2_gthrxn_in,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           gt2_rxdlyen_in,
    input           gt2_rxdlysreset_in,
    output          gt2_rxdlysresetdone_out,
    input           gt2_rxphalign_in,
    output          gt2_rxphaligndone_out,
    input           gt2_rxphalignen_in,
    input           gt2_rxphdlyreset_in,
    output  [4:0]   gt2_rxphmonitor_out,
    output  [4:0]   gt2_rxphslipmonitor_out,
    input           gt2_rxsyncallin_in,
    output          gt2_rxsyncdone_out,
    input           gt2_rxsyncin_in,
    input           gt2_rxsyncmode_in,
    output          gt2_rxsyncout_out,
    //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
    output          gt2_rxbyteisaligned_out,
    output          gt2_rxbyterealign_out,
    output          gt2_rxcommadet_out,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           gt2_rxdfeagchold_in,
    input           gt2_rxdfelfhold_in,
    output  [6:0]   gt2_rxmonitorout_out,
    input   [1:0]   gt2_rxmonitorsel_in,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          gt2_rxoutclk_out,
    output          gt2_rxoutclkfabric_out,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           gt2_gtrxreset_in,
    //---------------------- Receive Ports -RX AFE Ports -----------------------
    input           gt2_gthrxp_in,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          gt2_rxresetdone_out,
    //------------------- TX Initialization and Reset Ports --------------------
    input           gt2_gttxreset_in,
    input           gt2_txuserrdy_in,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           gt2_txusrclk_in,
    input           gt2_txusrclk2_in,
    //---------------- Transmit Ports - TX Buffer Bypass Ports -----------------
    input           gt2_txdlyen_in,
    input           gt2_txdlysreset_in,
    output          gt2_txdlysresetdone_out,
    input           gt2_txphalign_in,
    output          gt2_txphaligndone_out,
    input           gt2_txphalignen_in,
    input           gt2_txphdlyreset_in,
    input           gt2_txphinit_in,
    output          gt2_txphinitdone_out,
    //------------- Transmit Ports - TX Configurable Driver Ports --------------
    input           gt2_txinhibit_in,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [63:0]  gt2_txdata_in,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          gt2_gthtxn_out,
    output          gt2_gthtxp_out,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          gt2_txoutclk_out,
    output          gt2_txoutclkfabric_out,
    output          gt2_txoutclkpcs_out,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          gt2_txresetdone_out,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT3  (X0Y15)
    //____________________________CHANNEL PORTS________________________________
output gt3_rxpmaresetdone_out,
output gt3_txpmaresetdone_out,
    //------------------------ Channel - Clocking Ports ------------------------
    input           gt3_gtnorthrefclk0_in,
    input           gt3_gtnorthrefclk1_in,
    input           gt3_gtsouthrefclk0_in,
    input           gt3_gtsouthrefclk1_in,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   gt3_drpaddr_in,
    input           gt3_drpclk_in,
    input   [15:0]  gt3_drpdi_in,
    output  [15:0]  gt3_drpdo_out,
    input           gt3_drpen_in,
    output          gt3_drprdy_out,
    input           gt3_drpwe_in,
    //----------------------------- Clocking Ports -----------------------------
    input   [1:0]   gt3_rxsysclksel_in,
    input   [1:0]   gt3_txsysclksel_in,
    //----------------------------- Loopback Ports -----------------------------
    input   [2:0]   gt3_loopback_in,
    //------------------- RX Initialization and Reset Ports --------------------
    input           gt3_eyescanreset_in,
    input           gt3_rxuserrdy_in,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          gt3_eyescandataerror_out,
    input           gt3_eyescantrigger_in,
    //----------------------- Receive Ports - CDR Ports ------------------------
    input           gt3_rxcdrhold_in,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    input           gt3_rxslide_in,
    //----------------- Receive Ports - Digital Monitor Ports ------------------
    output  [14:0]  gt3_dmonitorout_out,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           gt3_rxusrclk_in,
    input           gt3_rxusrclk2_in,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [63:0]  gt3_rxdata_out,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           gt3_gthrxn_in,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           gt3_rxdlyen_in,
    input           gt3_rxdlysreset_in,
    output          gt3_rxdlysresetdone_out,
    input           gt3_rxphalign_in,
    output          gt3_rxphaligndone_out,
    input           gt3_rxphalignen_in,
    input           gt3_rxphdlyreset_in,
    output  [4:0]   gt3_rxphmonitor_out,
    output  [4:0]   gt3_rxphslipmonitor_out,
    input           gt3_rxsyncallin_in,
    output          gt3_rxsyncdone_out,
    input           gt3_rxsyncin_in,
    input           gt3_rxsyncmode_in,
    output          gt3_rxsyncout_out,
    //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
    output          gt3_rxbyteisaligned_out,
    output          gt3_rxbyterealign_out,
    output          gt3_rxcommadet_out,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           gt3_rxdfeagchold_in,
    input           gt3_rxdfelfhold_in,
    output  [6:0]   gt3_rxmonitorout_out,
    input   [1:0]   gt3_rxmonitorsel_in,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          gt3_rxoutclk_out,
    output          gt3_rxoutclkfabric_out,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           gt3_gtrxreset_in,
    //---------------------- Receive Ports -RX AFE Ports -----------------------
    input           gt3_gthrxp_in,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          gt3_rxresetdone_out,
    //------------------- TX Initialization and Reset Ports --------------------
    input           gt3_gttxreset_in,
    input           gt3_txuserrdy_in,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           gt3_txusrclk_in,
    input           gt3_txusrclk2_in,
    //---------------- Transmit Ports - TX Buffer Bypass Ports -----------------
    input           gt3_txdlyen_in,
    input           gt3_txdlysreset_in,
    output          gt3_txdlysresetdone_out,
    input           gt3_txphalign_in,
    output          gt3_txphaligndone_out,
    input           gt3_txphalignen_in,
    input           gt3_txphdlyreset_in,
    input           gt3_txphinit_in,
    output          gt3_txphinitdone_out,
    //------------- Transmit Ports - TX Configurable Driver Ports --------------
    input           gt3_txinhibit_in,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [63:0]  gt3_txdata_in,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          gt3_gthtxn_out,
    output          gt3_gthtxp_out,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          gt3_txoutclk_out,
    output          gt3_txoutclkfabric_out,
    output          gt3_txoutclkpcs_out,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          gt3_txresetdone_out,


    //____________________________COMMON PORTS________________________________
     input           gt0_qplloutclk_in,
     input           gt0_qplloutrefclk_in

);
//***************************** Parameter Declarations ************************
    localparam QPLL_FBDIV_TOP =  64;

    localparam QPLL_FBDIV_IN  =  (QPLL_FBDIV_TOP == 16)  ? 10'b0000100000 : 
				(QPLL_FBDIV_TOP == 20)  ? 10'b0000110000 :
				(QPLL_FBDIV_TOP == 32)  ? 10'b0001100000 :
				(QPLL_FBDIV_TOP == 40)  ? 10'b0010000000 :
				(QPLL_FBDIV_TOP == 64)  ? 10'b0011100000 :
				(QPLL_FBDIV_TOP == 66)  ? 10'b0101000000 :
				(QPLL_FBDIV_TOP == 80)  ? 10'b0100100000 :
				(QPLL_FBDIV_TOP == 100) ? 10'b0101110000 : 10'b0000000000;

   localparam QPLL_FBDIV_RATIO = (QPLL_FBDIV_TOP == 16)  ? 1'b1 : 
				(QPLL_FBDIV_TOP == 20)  ? 1'b1 :
				(QPLL_FBDIV_TOP == 32)  ? 1'b1 :
				(QPLL_FBDIV_TOP == 40)  ? 1'b1 :
				(QPLL_FBDIV_TOP == 64)  ? 1'b1 :
				(QPLL_FBDIV_TOP == 66)  ? 1'b0 :
				(QPLL_FBDIV_TOP == 80)  ? 1'b1 :
				(QPLL_FBDIV_TOP == 100) ? 1'b1 : 1'b1;

//***************************** Wire Declarations *****************************

    // ground and vcc signals
wire            tied_to_ground_i;
wire    [63:0]  tied_to_ground_vec_i;
wire            tied_to_vcc_i;
wire    [63:0]  tied_to_vcc_vec_i;
wire            gt0_qpllclk_i;
wire            gt0_qpllrefclk_i;
wire            gt1_qpllclk_i;
wire            gt1_qpllrefclk_i;
wire            gt2_qpllclk_i;
wire            gt2_qpllrefclk_i;
wire            gt3_qpllclk_i;
wire            gt3_qpllrefclk_i;

wire            gt0_cpllreset_i;
wire            gt0_cpllpd_i;
wire            gt1_cpllreset_i;
wire            gt1_cpllpd_i;
wire            gt2_cpllreset_i;
wire            gt2_cpllpd_i;
wire            gt3_cpllreset_i;
wire            gt3_cpllpd_i;
         
//********************************* Main Body of Code**************************

    assign tied_to_ground_i             = 1'b0;
    assign tied_to_ground_vec_i         = 64'h0000000000000000;
    assign tied_to_vcc_i                = 1'b1;
    assign tied_to_vcc_vec_i            = 64'hffffffffffffffff;


    assign  gt0_qpllclk_i    = gt0_qplloutclk_in;  
    assign  gt0_qpllrefclk_i = gt0_qplloutrefclk_in; 
    assign  gt1_qpllclk_i    = gt0_qplloutclk_in;  
    assign  gt1_qpllrefclk_i = gt0_qplloutrefclk_in; 
    assign  gt2_qpllclk_i    = gt0_qplloutclk_in;  
    assign  gt2_qpllrefclk_i = gt0_qplloutrefclk_in; 
    assign  gt3_qpllclk_i    = gt0_qplloutclk_in;  
    assign  gt3_qpllrefclk_i = gt0_qplloutrefclk_in; 
 

//------------------------- GT Instances  -------------------------------
    //_________________________________________________________________________
    //_________________________________________________________________________
//GT0   X0Y12
    clock_test_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP),
        .EXAMPLE_SIMULATION       (EXAMPLE_SIMULATION),
        .TXSYNC_OVRD_IN           (1'b1),
        .SIM_CPLLREFCLK_SEL       (3'b001),
        .TXSYNC_MULTILANE_IN      (1'b0) 
    )
gt0_clock_test_i
    (
        .rxpmaresetdone                 (gt0_rxpmaresetdone_out),
        .txpmaresetdone                 (gt0_txpmaresetdone_out),
        .cpllrefclksel_in(3'b001),
        //------------------------ Channel - Clocking Ports ------------------------
        .gtnorthrefclk0_in              (gt0_gtnorthrefclk0_in),
        .gtnorthrefclk1_in              (gt0_gtnorthrefclk1_in),
        .gtsouthrefclk0_in              (gt0_gtsouthrefclk0_in),
        .gtsouthrefclk1_in              (gt0_gtsouthrefclk1_in),
        //-------------------------- Channel - DRP Ports  --------------------------
        .drpaddr_in                     (gt0_drpaddr_in),
        .drpclk_in                      (gt0_drpclk_in),
        .drpdi_in                       (gt0_drpdi_in),
        .drpdo_out                      (gt0_drpdo_out),
        .drpen_in                       (gt0_drpen_in),
        .drprdy_out                     (gt0_drprdy_out),
        .drpwe_in                       (gt0_drpwe_in),
        //----------------------------- Clocking Ports -----------------------------
        .qpllclk_in                     (gt0_qpllclk_i),
        .qpllrefclk_in                  (gt0_qpllrefclk_i),
        .rxsysclksel_in                 (gt0_rxsysclksel_in),
        .txsysclksel_in                 (gt0_txsysclksel_in),
        //----------------------------- Loopback Ports -----------------------------
        .loopback_in                    (gt0_loopback_in),
        //------------------- RX Initialization and Reset Ports --------------------
        .eyescanreset_in                (gt0_eyescanreset_in),
        .rxuserrdy_in                   (gt0_rxuserrdy_in),
        //------------------------ RX Margin Analysis Ports ------------------------
        .eyescandataerror_out           (gt0_eyescandataerror_out),
        .eyescantrigger_in              (gt0_eyescantrigger_in),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .rxcdrhold_in                   (gt0_rxcdrhold_in),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .rxslide_in                     (gt0_rxslide_in),
        //----------------- Receive Ports - Digital Monitor Ports ------------------
        .dmonitorout_out                (gt0_dmonitorout_out),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .rxusrclk_in                    (gt0_rxusrclk_in),
        .rxusrclk2_in                   (gt0_rxusrclk2_in),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .rxdata_out                     (gt0_rxdata_out),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gthrxn_in                      (gt0_gthrxn_in),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .rxdlyen_in                     (gt0_rxdlyen_in),
        .rxdlysreset_in                 (gt0_rxdlysreset_in),
        .rxdlysresetdone_out            (gt0_rxdlysresetdone_out),
        .rxphalign_in                   (gt0_rxphalign_in),
        .rxphaligndone_out              (gt0_rxphaligndone_out),
        .rxphalignen_in                 (gt0_rxphalignen_in),
        .rxphdlyreset_in                (gt0_rxphdlyreset_in),
        .rxphmonitor_out                (gt0_rxphmonitor_out),
        .rxphslipmonitor_out            (gt0_rxphslipmonitor_out),
        .rxsyncallin_in                 (gt0_rxsyncallin_in),
        .rxsyncdone_out                 (gt0_rxsyncdone_out),
        .rxsyncin_in                    (gt0_rxsyncin_in),
        .rxsyncmode_in                  (gt0_rxsyncmode_in),
        .rxsyncout_out                  (gt0_rxsyncout_out),
        //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
        .rxbyteisaligned_out            (gt0_rxbyteisaligned_out),
        .rxbyterealign_out              (gt0_rxbyterealign_out),
        .rxcommadet_out                 (gt0_rxcommadet_out),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .rxdfeagchold_in                (gt0_rxdfeagchold_in),
        .rxdfelfhold_in                 (gt0_rxdfelfhold_in),
        .rxmonitorout_out               (gt0_rxmonitorout_out),
        .rxmonitorsel_in                (gt0_rxmonitorsel_in),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .rxoutclk_out                   (gt0_rxoutclk_out),
        .rxoutclkfabric_out             (gt0_rxoutclkfabric_out),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gtrxreset_in                   (gt0_gtrxreset_in),
        //---------------------- Receive Ports -RX AFE Ports -----------------------
        .gthrxp_in                      (gt0_gthrxp_in),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .rxresetdone_out                (gt0_rxresetdone_out),
        //------------------- TX Initialization and Reset Ports --------------------
        .gttxreset_in                   (gt0_gttxreset_in),
        .txuserrdy_in                   (gt0_txuserrdy_in),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .txusrclk_in                    (gt0_txusrclk_in),
        .txusrclk2_in                   (gt0_txusrclk2_in),
        //---------------- Transmit Ports - TX Buffer Bypass Ports -----------------
        .txdlyen_in                     (gt0_txdlyen_in),
        .txdlysreset_in                 (gt0_txdlysreset_in),
        .txdlysresetdone_out            (gt0_txdlysresetdone_out),
        .txphalign_in                   (gt0_txphalign_in),
        .txphaligndone_out              (gt0_txphaligndone_out),
        .txphalignen_in                 (gt0_txphalignen_in),
        .txphdlyreset_in                (gt0_txphdlyreset_in),
        .txphinit_in                    (gt0_txphinit_in),
        .txphinitdone_out               (gt0_txphinitdone_out),
        //------------- Transmit Ports - TX Configurable Driver Ports --------------
        .txinhibit_in                   (gt0_txinhibit_in),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .txdata_in                      (gt0_txdata_in),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gthtxn_out                     (gt0_gthtxn_out),
        .gthtxp_out                     (gt0_gthtxp_out),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .txoutclk_out                   (gt0_txoutclk_out),
        .txoutclkfabric_out             (gt0_txoutclkfabric_out),
        .txoutclkpcs_out                (gt0_txoutclkpcs_out),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .txresetdone_out                (gt0_txresetdone_out)

    );
    
    //_________________________________________________________________________
    //_________________________________________________________________________
//GT1   X0Y13
    clock_test_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP),
        .EXAMPLE_SIMULATION       (EXAMPLE_SIMULATION),
        .TXSYNC_OVRD_IN           (1'b1),
        .SIM_CPLLREFCLK_SEL       (3'b001),
        .TXSYNC_MULTILANE_IN      (1'b0) 
    )
gt1_clock_test_i
    (
        .rxpmaresetdone                 (gt1_rxpmaresetdone_out),
        .txpmaresetdone                 (gt1_txpmaresetdone_out),
        .cpllrefclksel_in(3'b001),
        //------------------------ Channel - Clocking Ports ------------------------
        .gtnorthrefclk0_in              (gt1_gtnorthrefclk0_in),
        .gtnorthrefclk1_in              (gt1_gtnorthrefclk1_in),
        .gtsouthrefclk0_in              (gt1_gtsouthrefclk0_in),
        .gtsouthrefclk1_in              (gt1_gtsouthrefclk1_in),
        //-------------------------- Channel - DRP Ports  --------------------------
        .drpaddr_in                     (gt1_drpaddr_in),
        .drpclk_in                      (gt1_drpclk_in),
        .drpdi_in                       (gt1_drpdi_in),
        .drpdo_out                      (gt1_drpdo_out),
        .drpen_in                       (gt1_drpen_in),
        .drprdy_out                     (gt1_drprdy_out),
        .drpwe_in                       (gt1_drpwe_in),
        //----------------------------- Clocking Ports -----------------------------
        .qpllclk_in                     (gt1_qpllclk_i),
        .qpllrefclk_in                  (gt1_qpllrefclk_i),
        .rxsysclksel_in                 (gt1_rxsysclksel_in),
        .txsysclksel_in                 (gt1_txsysclksel_in),
        //----------------------------- Loopback Ports -----------------------------
        .loopback_in                    (gt1_loopback_in),
        //------------------- RX Initialization and Reset Ports --------------------
        .eyescanreset_in                (gt1_eyescanreset_in),
        .rxuserrdy_in                   (gt1_rxuserrdy_in),
        //------------------------ RX Margin Analysis Ports ------------------------
        .eyescandataerror_out           (gt1_eyescandataerror_out),
        .eyescantrigger_in              (gt1_eyescantrigger_in),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .rxcdrhold_in                   (gt1_rxcdrhold_in),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .rxslide_in                     (gt1_rxslide_in),
        //----------------- Receive Ports - Digital Monitor Ports ------------------
        .dmonitorout_out                (gt1_dmonitorout_out),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .rxusrclk_in                    (gt1_rxusrclk_in),
        .rxusrclk2_in                   (gt1_rxusrclk2_in),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .rxdata_out                     (gt1_rxdata_out),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gthrxn_in                      (gt1_gthrxn_in),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .rxdlyen_in                     (gt1_rxdlyen_in),
        .rxdlysreset_in                 (gt1_rxdlysreset_in),
        .rxdlysresetdone_out            (gt1_rxdlysresetdone_out),
        .rxphalign_in                   (gt1_rxphalign_in),
        .rxphaligndone_out              (gt1_rxphaligndone_out),
        .rxphalignen_in                 (gt1_rxphalignen_in),
        .rxphdlyreset_in                (gt1_rxphdlyreset_in),
        .rxphmonitor_out                (gt1_rxphmonitor_out),
        .rxphslipmonitor_out            (gt1_rxphslipmonitor_out),
        .rxsyncallin_in                 (gt1_rxsyncallin_in),
        .rxsyncdone_out                 (gt1_rxsyncdone_out),
        .rxsyncin_in                    (gt1_rxsyncin_in),
        .rxsyncmode_in                  (gt1_rxsyncmode_in),
        .rxsyncout_out                  (gt1_rxsyncout_out),
        //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
        .rxbyteisaligned_out            (gt1_rxbyteisaligned_out),
        .rxbyterealign_out              (gt1_rxbyterealign_out),
        .rxcommadet_out                 (gt1_rxcommadet_out),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .rxdfeagchold_in                (gt1_rxdfeagchold_in),
        .rxdfelfhold_in                 (gt1_rxdfelfhold_in),
        .rxmonitorout_out               (gt1_rxmonitorout_out),
        .rxmonitorsel_in                (gt1_rxmonitorsel_in),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .rxoutclk_out                   (gt1_rxoutclk_out),
        .rxoutclkfabric_out             (gt1_rxoutclkfabric_out),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gtrxreset_in                   (gt1_gtrxreset_in),
        //---------------------- Receive Ports -RX AFE Ports -----------------------
        .gthrxp_in                      (gt1_gthrxp_in),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .rxresetdone_out                (gt1_rxresetdone_out),
        //------------------- TX Initialization and Reset Ports --------------------
        .gttxreset_in                   (gt1_gttxreset_in),
        .txuserrdy_in                   (gt1_txuserrdy_in),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .txusrclk_in                    (gt1_txusrclk_in),
        .txusrclk2_in                   (gt1_txusrclk2_in),
        //---------------- Transmit Ports - TX Buffer Bypass Ports -----------------
        .txdlyen_in                     (gt1_txdlyen_in),
        .txdlysreset_in                 (gt1_txdlysreset_in),
        .txdlysresetdone_out            (gt1_txdlysresetdone_out),
        .txphalign_in                   (gt1_txphalign_in),
        .txphaligndone_out              (gt1_txphaligndone_out),
        .txphalignen_in                 (gt1_txphalignen_in),
        .txphdlyreset_in                (gt1_txphdlyreset_in),
        .txphinit_in                    (gt1_txphinit_in),
        .txphinitdone_out               (gt1_txphinitdone_out),
        //------------- Transmit Ports - TX Configurable Driver Ports --------------
        .txinhibit_in                   (gt1_txinhibit_in),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .txdata_in                      (gt1_txdata_in),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gthtxn_out                     (gt1_gthtxn_out),
        .gthtxp_out                     (gt1_gthtxp_out),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .txoutclk_out                   (gt1_txoutclk_out),
        .txoutclkfabric_out             (gt1_txoutclkfabric_out),
        .txoutclkpcs_out                (gt1_txoutclkpcs_out),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .txresetdone_out                (gt1_txresetdone_out)

    );
    
    //_________________________________________________________________________
    //_________________________________________________________________________
//GT2   X0Y14
    clock_test_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP),
        .EXAMPLE_SIMULATION       (EXAMPLE_SIMULATION),
        .TXSYNC_OVRD_IN           (1'b1),
        .SIM_CPLLREFCLK_SEL       (3'b001),
        .TXSYNC_MULTILANE_IN      (1'b0) 
    )
gt2_clock_test_i
    (
        .rxpmaresetdone                 (gt2_rxpmaresetdone_out),
        .txpmaresetdone                 (gt2_txpmaresetdone_out),
        .cpllrefclksel_in(3'b001),
        //------------------------ Channel - Clocking Ports ------------------------
        .gtnorthrefclk0_in              (gt2_gtnorthrefclk0_in),
        .gtnorthrefclk1_in              (gt2_gtnorthrefclk1_in),
        .gtsouthrefclk0_in              (gt2_gtsouthrefclk0_in),
        .gtsouthrefclk1_in              (gt2_gtsouthrefclk1_in),
        //-------------------------- Channel - DRP Ports  --------------------------
        .drpaddr_in                     (gt2_drpaddr_in),
        .drpclk_in                      (gt2_drpclk_in),
        .drpdi_in                       (gt2_drpdi_in),
        .drpdo_out                      (gt2_drpdo_out),
        .drpen_in                       (gt2_drpen_in),
        .drprdy_out                     (gt2_drprdy_out),
        .drpwe_in                       (gt2_drpwe_in),
        //----------------------------- Clocking Ports -----------------------------
        .qpllclk_in                     (gt2_qpllclk_i),
        .qpllrefclk_in                  (gt2_qpllrefclk_i),
        .rxsysclksel_in                 (gt2_rxsysclksel_in),
        .txsysclksel_in                 (gt2_txsysclksel_in),
        //----------------------------- Loopback Ports -----------------------------
        .loopback_in                    (gt2_loopback_in),
        //------------------- RX Initialization and Reset Ports --------------------
        .eyescanreset_in                (gt2_eyescanreset_in),
        .rxuserrdy_in                   (gt2_rxuserrdy_in),
        //------------------------ RX Margin Analysis Ports ------------------------
        .eyescandataerror_out           (gt2_eyescandataerror_out),
        .eyescantrigger_in              (gt2_eyescantrigger_in),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .rxcdrhold_in                   (gt2_rxcdrhold_in),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .rxslide_in                     (gt2_rxslide_in),
        //----------------- Receive Ports - Digital Monitor Ports ------------------
        .dmonitorout_out                (gt2_dmonitorout_out),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .rxusrclk_in                    (gt2_rxusrclk_in),
        .rxusrclk2_in                   (gt2_rxusrclk2_in),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .rxdata_out                     (gt2_rxdata_out),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gthrxn_in                      (gt2_gthrxn_in),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .rxdlyen_in                     (gt2_rxdlyen_in),
        .rxdlysreset_in                 (gt2_rxdlysreset_in),
        .rxdlysresetdone_out            (gt2_rxdlysresetdone_out),
        .rxphalign_in                   (gt2_rxphalign_in),
        .rxphaligndone_out              (gt2_rxphaligndone_out),
        .rxphalignen_in                 (gt2_rxphalignen_in),
        .rxphdlyreset_in                (gt2_rxphdlyreset_in),
        .rxphmonitor_out                (gt2_rxphmonitor_out),
        .rxphslipmonitor_out            (gt2_rxphslipmonitor_out),
        .rxsyncallin_in                 (gt2_rxsyncallin_in),
        .rxsyncdone_out                 (gt2_rxsyncdone_out),
        .rxsyncin_in                    (gt2_rxsyncin_in),
        .rxsyncmode_in                  (gt2_rxsyncmode_in),
        .rxsyncout_out                  (gt2_rxsyncout_out),
        //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
        .rxbyteisaligned_out            (gt2_rxbyteisaligned_out),
        .rxbyterealign_out              (gt2_rxbyterealign_out),
        .rxcommadet_out                 (gt2_rxcommadet_out),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .rxdfeagchold_in                (gt2_rxdfeagchold_in),
        .rxdfelfhold_in                 (gt2_rxdfelfhold_in),
        .rxmonitorout_out               (gt2_rxmonitorout_out),
        .rxmonitorsel_in                (gt2_rxmonitorsel_in),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .rxoutclk_out                   (gt2_rxoutclk_out),
        .rxoutclkfabric_out             (gt2_rxoutclkfabric_out),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gtrxreset_in                   (gt2_gtrxreset_in),
        //---------------------- Receive Ports -RX AFE Ports -----------------------
        .gthrxp_in                      (gt2_gthrxp_in),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .rxresetdone_out                (gt2_rxresetdone_out),
        //------------------- TX Initialization and Reset Ports --------------------
        .gttxreset_in                   (gt2_gttxreset_in),
        .txuserrdy_in                   (gt2_txuserrdy_in),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .txusrclk_in                    (gt2_txusrclk_in),
        .txusrclk2_in                   (gt2_txusrclk2_in),
        //---------------- Transmit Ports - TX Buffer Bypass Ports -----------------
        .txdlyen_in                     (gt2_txdlyen_in),
        .txdlysreset_in                 (gt2_txdlysreset_in),
        .txdlysresetdone_out            (gt2_txdlysresetdone_out),
        .txphalign_in                   (gt2_txphalign_in),
        .txphaligndone_out              (gt2_txphaligndone_out),
        .txphalignen_in                 (gt2_txphalignen_in),
        .txphdlyreset_in                (gt2_txphdlyreset_in),
        .txphinit_in                    (gt2_txphinit_in),
        .txphinitdone_out               (gt2_txphinitdone_out),
        //------------- Transmit Ports - TX Configurable Driver Ports --------------
        .txinhibit_in                   (gt2_txinhibit_in),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .txdata_in                      (gt2_txdata_in),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gthtxn_out                     (gt2_gthtxn_out),
        .gthtxp_out                     (gt2_gthtxp_out),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .txoutclk_out                   (gt2_txoutclk_out),
        .txoutclkfabric_out             (gt2_txoutclkfabric_out),
        .txoutclkpcs_out                (gt2_txoutclkpcs_out),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .txresetdone_out                (gt2_txresetdone_out)

    );
    
    //_________________________________________________________________________
    //_________________________________________________________________________
//GT3   X0Y15
    clock_test_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP),
        .EXAMPLE_SIMULATION       (EXAMPLE_SIMULATION),
        .TXSYNC_OVRD_IN           (1'b1),
        .SIM_CPLLREFCLK_SEL       (3'b001),
        .TXSYNC_MULTILANE_IN      (1'b0) 
    )
gt3_clock_test_i
    (
        .rxpmaresetdone                 (gt3_rxpmaresetdone_out),
        .txpmaresetdone                 (gt3_txpmaresetdone_out),
        .cpllrefclksel_in(3'b001),
        //------------------------ Channel - Clocking Ports ------------------------
        .gtnorthrefclk0_in              (gt3_gtnorthrefclk0_in),
        .gtnorthrefclk1_in              (gt3_gtnorthrefclk1_in),
        .gtsouthrefclk0_in              (gt3_gtsouthrefclk0_in),
        .gtsouthrefclk1_in              (gt3_gtsouthrefclk1_in),
        //-------------------------- Channel - DRP Ports  --------------------------
        .drpaddr_in                     (gt3_drpaddr_in),
        .drpclk_in                      (gt3_drpclk_in),
        .drpdi_in                       (gt3_drpdi_in),
        .drpdo_out                      (gt3_drpdo_out),
        .drpen_in                       (gt3_drpen_in),
        .drprdy_out                     (gt3_drprdy_out),
        .drpwe_in                       (gt3_drpwe_in),
        //----------------------------- Clocking Ports -----------------------------
        .qpllclk_in                     (gt3_qpllclk_i),
        .qpllrefclk_in                  (gt3_qpllrefclk_i),
        .rxsysclksel_in                 (gt3_rxsysclksel_in),
        .txsysclksel_in                 (gt3_txsysclksel_in),
        //----------------------------- Loopback Ports -----------------------------
        .loopback_in                    (gt3_loopback_in),
        //------------------- RX Initialization and Reset Ports --------------------
        .eyescanreset_in                (gt3_eyescanreset_in),
        .rxuserrdy_in                   (gt3_rxuserrdy_in),
        //------------------------ RX Margin Analysis Ports ------------------------
        .eyescandataerror_out           (gt3_eyescandataerror_out),
        .eyescantrigger_in              (gt3_eyescantrigger_in),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .rxcdrhold_in                   (gt3_rxcdrhold_in),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .rxslide_in                     (gt3_rxslide_in),
        //----------------- Receive Ports - Digital Monitor Ports ------------------
        .dmonitorout_out                (gt3_dmonitorout_out),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .rxusrclk_in                    (gt3_rxusrclk_in),
        .rxusrclk2_in                   (gt3_rxusrclk2_in),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .rxdata_out                     (gt3_rxdata_out),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gthrxn_in                      (gt3_gthrxn_in),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .rxdlyen_in                     (gt3_rxdlyen_in),
        .rxdlysreset_in                 (gt3_rxdlysreset_in),
        .rxdlysresetdone_out            (gt3_rxdlysresetdone_out),
        .rxphalign_in                   (gt3_rxphalign_in),
        .rxphaligndone_out              (gt3_rxphaligndone_out),
        .rxphalignen_in                 (gt3_rxphalignen_in),
        .rxphdlyreset_in                (gt3_rxphdlyreset_in),
        .rxphmonitor_out                (gt3_rxphmonitor_out),
        .rxphslipmonitor_out            (gt3_rxphslipmonitor_out),
        .rxsyncallin_in                 (gt3_rxsyncallin_in),
        .rxsyncdone_out                 (gt3_rxsyncdone_out),
        .rxsyncin_in                    (gt3_rxsyncin_in),
        .rxsyncmode_in                  (gt3_rxsyncmode_in),
        .rxsyncout_out                  (gt3_rxsyncout_out),
        //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
        .rxbyteisaligned_out            (gt3_rxbyteisaligned_out),
        .rxbyterealign_out              (gt3_rxbyterealign_out),
        .rxcommadet_out                 (gt3_rxcommadet_out),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .rxdfeagchold_in                (gt3_rxdfeagchold_in),
        .rxdfelfhold_in                 (gt3_rxdfelfhold_in),
        .rxmonitorout_out               (gt3_rxmonitorout_out),
        .rxmonitorsel_in                (gt3_rxmonitorsel_in),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .rxoutclk_out                   (gt3_rxoutclk_out),
        .rxoutclkfabric_out             (gt3_rxoutclkfabric_out),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gtrxreset_in                   (gt3_gtrxreset_in),
        //---------------------- Receive Ports -RX AFE Ports -----------------------
        .gthrxp_in                      (gt3_gthrxp_in),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .rxresetdone_out                (gt3_rxresetdone_out),
        //------------------- TX Initialization and Reset Ports --------------------
        .gttxreset_in                   (gt3_gttxreset_in),
        .txuserrdy_in                   (gt3_txuserrdy_in),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .txusrclk_in                    (gt3_txusrclk_in),
        .txusrclk2_in                   (gt3_txusrclk2_in),
        //---------------- Transmit Ports - TX Buffer Bypass Ports -----------------
        .txdlyen_in                     (gt3_txdlyen_in),
        .txdlysreset_in                 (gt3_txdlysreset_in),
        .txdlysresetdone_out            (gt3_txdlysresetdone_out),
        .txphalign_in                   (gt3_txphalign_in),
        .txphaligndone_out              (gt3_txphaligndone_out),
        .txphalignen_in                 (gt3_txphalignen_in),
        .txphdlyreset_in                (gt3_txphdlyreset_in),
        .txphinit_in                    (gt3_txphinit_in),
        .txphinitdone_out               (gt3_txphinitdone_out),
        //------------- Transmit Ports - TX Configurable Driver Ports --------------
        .txinhibit_in                   (gt3_txinhibit_in),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .txdata_in                      (gt3_txdata_in),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gthtxn_out                     (gt3_gthtxn_out),
        .gthtxp_out                     (gt3_gthtxp_out),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .txoutclk_out                   (gt3_txoutclk_out),
        .txoutclkfabric_out             (gt3_txoutclkfabric_out),
        .txoutclkpcs_out                (gt3_txoutclkpcs_out),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .txresetdone_out                (gt3_txresetdone_out)

    );
    
endmodule

