`timescale 1ns/1ps
//==============================================================================
// qwn_header_rom -- synchronous-read byte ROM (infers a Block RAM on 7-series:
// reg array + $readmemh init + registered read). Holds the burst header
// payload (structured header fields + BER/PRBS block), mirroring the
// reference design's BRAM-based frame generator. tx_burst_seq streams bytes
// from here during the HEADER and PAYLOAD phases.
//
//   addr  : byte address (present this cycle)
//   dout  : ROM[addr] registered (valid NEXT cycle -- 1-cycle BRAM latency)
//
// Contents are generated by work/gen_qwn_header.py -> qwn_header.mem
// (qwn_header.mem must be on the synth source path).
//==============================================================================
module qwn_header_rom #(
    parameter        AW   = 9,                 // 512-byte ROM
    parameter        DW   = 8,
    parameter        INIT = "qwn_header.mem"
)(
    input  wire            clk,
    input  wire [AW-1:0]   addr,
    output reg  [DW-1:0]   dout
);
    (* rom_style = "block" *) reg [DW-1:0] mem [0:(1<<AW)-1];

    integer i;
    initial begin
        for (i=0;i<(1<<AW);i=i+1) mem[i] = {DW{1'b0}};
        $readmemh(INIT, mem);
    end

    always @(posedge clk)
        dout <= mem[addr];
endmodule
